version: '3.4'

services:

  db:
    ports:
      - "8001:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpwd      

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest


  service1.api:
    ports:
      - "42000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_RabbitMQ_Connection=host=rabbitmq://rabbitmq;queue=usersQueue;user=guest;password=guest
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  service2.api:
    ports:
      - "42001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_RabbitMQ_Connection=host=rabbitmq://rabbitmq;queue=usersQueue;user=guest;password=guest
      - CUSTOMCONNSTR_DefaultConnection=Host=db;Port=5432;Database=Service2;Username=postgres;Password=dbpwd
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 
